"use strict";
exports.__esModule = true;
var express_1 = require("express");
var path_1 = require("path");
var cookie_parser_1 = require("cookie-parser");
var morgan_1 = require("morgan");
var index_1 = require("./routes/index");
var app = express_1["default"]();
app.use(morgan_1["default"]('dev'));
app.use(express_1["default"].json());
app.use(express_1["default"].urlencoded({ extended: false }));
app.use(cookie_parser_1["default"]());
app.use(express_1["default"].static(path_1["default"].resolve(__dirname, '../frontend/dist')));
app.use('/', index_1["default"]);
module.exports = app;
