export const EVENTS = {
  ADD_INVOICE: 'ADD_INVOICE',
  CLEAR_INVOICES: 'CLEAR_INVOICES',
  REMOVE_INVOICE: 'REMOVE_INVOICE',
  UPDATE_INVOICE: 'UPDATE_INVOICE',
  HIGHLIGHT_INVOICE: 'HIGHLIGHT_INVOICE',
  SET_SUM_EARNING: 'SET_SUM_EARNING',
  SET_SUM_SPENDING: 'SET_SUM_SPENDING',
  EARNING_TOGGLE: 'EARNING_TOGGLE',
  SPENDING_TOGGLE: 'SPENDING_TOGGLE',
}

export const ROUTER = {
  MUTATE_VIEW: 'MUTATE_VIEW',
}
