export const EVENTS = {
  ADD_INVOICE: 'ADD_INVOICE',
  CLEAR_INVOICES: 'CLEAR_INVOICES',
  REMOVE_INVOICE: 'REMOVE_INVOICE',
  SET_SUM_EARNING: 'SET_SUM_EARNING',
  SET_SUM_SPENDING: 'SET_SUM_SPENDING',
}
