export const EVENTS = {
  ADD_INVOICE: 'ADD_INVOICE',
  CLEAR_INVOICES: 'CLEAR_INVOICES',
  REMOVE_INVOICE: 'REMOVE_INVOICE',
  UPDATE_INVOICE: 'UPDATE_INVOICE',
  HIGHLIGHT_INVOICE: 'HIGHLIGHT_INVOICE',
  SET_SUM_EARNING: 'SET_SUM_EARNING',
  SET_SUM_SPENDING: 'SET_SUM_SPENDING',
  EARNING_TOGGLE: 'EARNING_TOGGLE',
  SPENDING_TOGGLE: 'SPENDING_TOGGLE',
}

export const FORM_CLASS = {
  INPUT_AMOUNT: 'input-amount',
  INPUT_DATE: 'input-date',
  INPUT_ITEM: 'input-item',
  SELECT_CATEGORY: 'select-category',
  SELECT_PAYMENT: 'select-payment',
  CLEAR_BTN: 'button-clear-form',
  REMOVE_BTN: 'button-remove-invoice',
}
